version: '3.4'

services:
  # smartdomaindrivendesign.ordersample:
  #   image: ${DOCKER_REGISTRY-}smartdomaindrivendesignordersample
  #   build:
  #     context: .
  #     dockerfile: SmartDomainDrivenDesign.OrderSample\Dockerfile

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    restart: unless-stopped
    # networks:
    #   - pacco
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    # networks:
    #   - pacco
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    # networks:
    #  - pacco
    ports:
      - 5341:80
    volumes: 
      - seq:/data

volumes:
  rabbitmq:
    driver: local
  redis:
    driver: local
  seq:
    driver: local
